### ISSUE TITLE
Display full path instead of just the last part segment

### ISSUE THREAD

**Issue by laurencee** [srisenthilkumar/har-viewer#13]
Given a `.har` with content queries such as
```json
{
    "name": ":method",
    "value": "GET"
},
{
    "name": ":path",
    "value": "/api/someresource/1234"
}
```

Right now the plugin just display
`GET 1234`

This doesn't really give me enough context to work with, instead it would be way more useful if the full path value was written out
`GET /api/someresource/1234`

If you prefer the first view perhaps this could be behind a config value? 
I'd think most people would prefer the second view though.

**Comment by srisenthilkumar** [comment]
I like this idea of making it configurable. Let me add it to the backlog.

**Comment by srisenthilkumar** [comment]
@laurencee 0.0.2 version is published it has the capability you were looking for, thanks for your suggestion. 

![image](https://user-images.githubusercontent.com/4751443/190887493-88cfef3b-1a3e-490a-b5cf-f5d05c61415e.png)
